#!/usr/bin/env bash
set -euo pipefail

APP_NAME="calabi-shell"
BEGIN_MARKER="# >>> ${APP_NAME} >>>"
END_MARKER="# <<< ${APP_NAME} <<<"
MODE="user"

usage() {
  cat <<USAGE
Usage: $0 [--system]

Options:
  --system   Install as a system-wide Bash default. Requires root.
  -h, --help Show this help.
USAGE
}

for arg in "$@"; do
  case "$arg" in
    --system)
      MODE="system"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf '[%s] ERROR: unknown argument: %s\n' "$APP_NAME" "$arg" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ "$MODE" = "system" ]; then
  [ "$(id -u)" -eq 0 ] || {
    printf '[%s] ERROR: --system requires root\n' "$APP_NAME" >&2
    exit 1
  }

  CONFIG_ROOT="/etc/xdg"
  APP_CONFIG_DIR="${CONFIG_ROOT}/${APP_NAME}"
  STARSHIP_CONFIG_PATH="${APP_CONFIG_DIR}/starship.toml"
  BASHRC_PATH="/etc/bashrc"
  PROFILE_SNIPPET_PATH="/etc/profile.d/${APP_NAME}.sh"
  BIN_DIR="/usr/local/bin"
else
  CONFIG_ROOT="${XDG_CONFIG_HOME:-$HOME/.config}"
  APP_CONFIG_DIR="${CONFIG_ROOT}/${APP_NAME}"
  STARSHIP_CONFIG_PATH="${APP_CONFIG_DIR}/starship.toml"
  BASHRC_PATH="${HOME}/.bashrc"
  PROFILE_SNIPPET_PATH=""
  BIN_DIR="${HOME}/.local/bin"
fi

log() {
  printf '[%s] %s\n' "$APP_NAME" "$*"
}

fail() {
  printf '[%s] ERROR: %s\n' "$APP_NAME" "$*" >&2
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

remove_managed_block() {
  local file="$1"
  [ -f "$file" ] || return 0

  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { skip=1; next }
    $0 == end   { skip=0; next }
    !skip       { print }
  ' "$file" > "${file}.tmp"

  mv "${file}.tmp" "$file"
}

check_platform_support() {
  local os_release="/etc/os-release"
  [ -r "$os_release" ] || fail "cannot read $os_release"

  # shellcheck disable=SC1091
  . "$os_release"

  local major="${VERSION_ID%%.*}"
  case "${ID:-}" in
    fedora)
      [ "$major" -ge 43 ] || fail "unsupported platform: Fedora ${VERSION_ID:-unknown}. calabi-shell supports Fedora 43+ only"
      ;;
    rhel)
      [ "$major" -ge 10 ] || fail "unsupported platform: RHEL ${VERSION_ID:-unknown}. calabi-shell supports RHEL 10+ only"
      ;;
    *)
      fail "unsupported platform: ${PRETTY_NAME:-${ID:-unknown}}. calabi-shell supports Fedora 43+ and RHEL 10+ only"
      ;;
  esac
}

ensure_prereqs() {
  have bash || fail "bash is required"
  have awk || fail "awk is required"
  have date || fail "date is required"
  have install || fail "install is required"
  have grep || fail "grep is required"

  check_platform_support

  if ! have starship; then
    have curl || fail "curl is required to install starship"
    have sh || fail "sh is required to run the starship installer"
  fi
}

install_starship() {
  if have starship; then
    log "starship already present at $(command -v starship)"
    return 0
  fi

  mkdir -p "$BIN_DIR"
  log "installing starship to ${BIN_DIR}"
  curl -fsSL https://starship.rs/install.sh | sh -s -- -y -b "$BIN_DIR"

  if ! PATH="$BIN_DIR:$PATH" command -v starship >/dev/null 2>&1; then
    fail "starship installation completed but the binary was not found in ${BIN_DIR}"
  fi
}

install_config() {
  mkdir -p "$APP_CONFIG_DIR"
  install -m 0644 "$(dirname "$0")/starship.toml" "$STARSHIP_CONFIG_PATH"
  log "installed Starship config to ${STARSHIP_CONFIG_PATH}"
}

install_profile_snippet() {
  [ "$MODE" = "system" ] || return 0

  cat > "$PROFILE_SNIPPET_PATH" <<PROFILE_SNIPPET
# Generated by ${APP_NAME} --system
case ":\$PATH:" in
  *":${BIN_DIR}:"*) ;;
  *) export PATH="${BIN_DIR}:\$PATH" ;;
esac
export STARSHIP_CONFIG="${STARSHIP_CONFIG_PATH}"
PROFILE_SNIPPET

  chmod 0644 "$PROFILE_SNIPPET_PATH"
  log "installed ${PROFILE_SNIPPET_PATH}"
}

install_bashrc_block() {
  touch "$BASHRC_PATH"
  remove_managed_block "$BASHRC_PATH"

  if [ "$MODE" = "system" ]; then
    cat >> "$BASHRC_PATH" <<BASHRC_BLOCK

$BEGIN_MARKER
case ":\$PATH:" in
  *":${BIN_DIR}:"*) ;;
  *) export PATH="${BIN_DIR}:\$PATH" ;;
esac
export STARSHIP_CONFIG="${STARSHIP_CONFIG_PATH}"
if [ -n "\${BASH_VERSION:-}" ] && [[ "\$-" == *i* ]] && command -v starship >/dev/null 2>&1; then
  eval "\$(starship init bash)"
fi
$END_MARKER
BASHRC_BLOCK
  else
    cat >> "$BASHRC_PATH" <<BASHRC_BLOCK

$BEGIN_MARKER
case ":\$PATH:" in
  *":\$HOME/.local/bin:"*) ;;
  *) export PATH="\$HOME/.local/bin:\$PATH" ;;
esac
export STARSHIP_CONFIG="\${XDG_CONFIG_HOME:-\$HOME/.config}/${APP_NAME}/starship.toml"
if [ -n "\${BASH_VERSION:-}" ] && [[ "\$-" == *i* ]] && command -v starship >/dev/null 2>&1; then
  eval "\$(starship init bash)"
fi
$END_MARKER
BASHRC_BLOCK
  fi

  log "updated ${BASHRC_PATH}"
}

main() {
  ensure_prereqs
  install_starship
  install_config
  install_profile_snippet
  install_bashrc_block

  log "done"
  if [ "$MODE" = "system" ]; then
    log "system mode installed a managed block in ${BASHRC_PATH} and ${PROFILE_SNIPPET_PATH}"
    log "new shells will pick this up; existing shells can run: exec bash -l"
  else
    log "restart your shell or run: exec bash -l"
  fi
  log "note: this prompt uses Nerd Font glyphs; configure a Nerd Font in your terminal if symbols look wrong"
}

main "$@"
